name: go
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  file_picker: ^10.3.2
  path_provider: ^2.1.5
  fluttertoast: ^8.2.2
  open_filex: ^4.5.0
  connectivity_plus: ^6.1.5
  network_info_plus: ^6.1.4
  permission_handler: ^12.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true